### PR TITLE
123

### PR DESCRIPTION
**Pull request by amrztoo**
12345

---
This change is [Reviewable](https://reviewable.io/reviews/amarrazali/rrms/9)

### CODE REVIEW

**Review by amrztoo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/amarrazali/rrms/9#-:-MrYliGA3MjSUapzuVaN:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by AmarRazali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/amarrazali/rrms/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AmarRazali and @amrztoo)

___
*[test reviewable2, line 1 at r1](https://reviewable.io/reviews/amarrazali/rrms/9#-MrYm6q3A8r7O8njT2eU:-MrYm6q3A8r7O8njT2eV:b-hfs2cp) ([raw file](https://github.com/amarrazali/rrms/blob/cf0484c674f610dded36ac1a2f965fa43508159c/test%20reviewable2#L1)):*
> ```
> test
> ```

check spelling

**Comment by AmarRazali** [comment]
___
*[test reviewable2, line 4 at r1](https://reviewable.io/reviews/amarrazali/rrms/9#-MrYmJ6z4beJbAqSVXLG:-MrYmJ6z4beJbAqSVXLH:b-jgid5b) ([raw file](https://github.com/amarrazali/rrms/blob/cf0484c674f610dded36ac1a2f965fa43508159c/test%20reviewable2#L4)):*
> ```
> 
> test2
> ```

ehleofle

**Comment by AmarRazali** [comment]
___
*[test reviewable2, line 4 at r1](https://reviewable.io/reviews/amarrazali/rrms/9#-MrYmJ6z4beJbAqSVXLG:-MrYmMmU8F1LWMbdKEoW:b-mj8did) ([raw file](https://github.com/amarrazali/rrms/blob/cf0484c674f610dded36ac1a2f965fa43508159c/test%20reviewable2#L4)):*
<details><summary><i>Previously, AmarRazali wrote…</i></summary><blockquote>

ehleofle
</blockquote></details>

hdsnhds

**Review by AmarRazali — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/amarrazali/rrms/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amrztoo)

**Pull request merged**
