### PR TITLE
Create test review file

### PR DESCRIPTION
**Pull request by amrztoo**
pull request for review

---
This change is [Reviewable](https://reviewable.io/reviews/amarrazali/rrms/14)

### CODE REVIEW

**Comment by AmarRazali** [comment]
___
*[test review file, line 1 at r1](https://reviewable.io/reviews/amarrazali/rrms/14#-MrcBO4Y0L55aSKvjI9e:-MrcBO4Y0L55aSKvjI9f:bq2nq7i) ([raw file](https://github.com/amarrazali/rrms/blob/4c3d1897910ffc9a3a3aa714149791c85672313f/test%20review%20file#L1)):*
> ```
> <div class="flex flex-wrap">
> ```

what css did you use?

**Review by amarrazali — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/amarrazali/rrms/14)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @AmarRazali and @amrztoo)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/amarrazali/rrms/14#-MrcBBoJ6ADoxrcp9JKe):*
dont make commit without my permission
___
*[test review file, line 2 at r1](https://reviewable.io/reviews/amarrazali/rrms/14#-MrcBXYGA3L7ZJ5bG4xe:-MrcBXYH1bL1klV4Nd5L:b-k0b7x7) ([raw file](https://github.com/amarrazali/rrms/blob/4c3d1897910ffc9a3a3aa714149791c85672313f/test%20review%20file#L2)):*
> ```
> <div class="flex flex-wrap">
>     @foreach($products as $product)
> ```

use do while instead of foreach

**Review by amrztoo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/amarrazali/rrms/14)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @AmarRazali)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/amarrazali/rrms/14#-MrcBBoJ6ADoxrcp9JKe):*
<details><summary><i>Previously, AmarRazali wrote…</i></summary><blockquote>

dont make commit without my permission
</blockquote></details>

noted
___
*[test review file, line 1 at r1](https://reviewable.io/reviews/amarrazali/rrms/14#-MrcBO4Y0L55aSKvjI9e:-MrcCAaw3jHgwEpnd-Wf:bophefx) ([raw file](https://github.com/amarrazali/rrms/blob/4c3d1897910ffc9a3a3aa714149791c85672313f/test%20review%20file#L1)):*
<details><summary><i>Previously, AmarRazali wrote…</i></summary><blockquote>

what css did you use?
</blockquote></details>

tailwind
___
*[test review file, line 2 at r1](https://reviewable.io/reviews/amarrazali/rrms/14#-MrcBXYGA3L7ZJ5bG4xe:-MrcCDwsBGgT06eEE0oB:b-896fix) ([raw file](https://github.com/amarrazali/rrms/blob/4c3d1897910ffc9a3a3aa714149791c85672313f/test%20review%20file#L2)):*
<details><summary><i>Previously, AmarRazali wrote…</i></summary><blockquote>

use do while instead of foreach
</blockquote></details>

Done.

**Review by amarrazali — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/amarrazali/rrms/14#-:-MrcCX1KBlS1kH-in2dR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amrztoo)

**Pull request merged**
